import { useState } from 'react';
import Head from 'next/head';

import Navbar from '@/components/Navbar';
import ColorWheel from '@/components/ColorWheel';
import SelectMode from '@/components/SelectMode';
import PickPrimaryColor from '@/components/PickPrimaryColor';
import ColorPaletteGroup from '@/components/ColorPaletteGroup';
import Components from '@/components/components';

import Color from 'color';

const modes = [
  { id: 'complementary', name: 'Complementary' },
  { id: 'monochromatic', name: 'Monochromatic' },
  { id: 'analogous', name: 'Analogous' },
  { id: 'triadic', name: 'Triadic' },
  { id: 'tetradic', name: 'Tetradic' },
];

export default function Home() {
  const [inputColor, setInputColor] = useState('#f43f5e');
  const [colors, setColors] = useState([]);
  const [mode, setMode] = useState(modes[0].id);

  const [copied, setCopied] = useState(false);
  const [copyIndex, setCopyIndex] = useState(0);

  const copyToClipboard = (color, index) => {
    setCopied(true);
    setCopyIndex(index);
    navigator.clipboard.writeText(color);

    setTimeout(() => {
      setCopied(false);
    }, 1500);
  };

  return (
    <>
      <Head>
        <title>HueHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="min-h-screen">
        <div
          className="absolute top-0 left-0 right-0 -z-10 h-[65rem] bg-[url('../public/wave.webp')] bg-bottom bg-no-repeat"
          style={{ backgroundColor: colors[0] }}
        />

        <div className="mx-auto max-w-7xl px-6 py-14 lg:flex lg:items-center lg:gap-x-10 lg:px-8">
          <div className="mx-auto max-w-2xl lg:mx-0 lg:flex-auto">
            <h1
              className="max-w-lg text-4xl font-medium tracking-tight sm:text-6xl"
              style={{ color: Color(colors[0]).isDark() ? 'white' : '#111827' }}
            >
              Create your own color palette
            </h1>
            <p
              className="mt-6 text-lg leading-8 opacity-70"
              style={{ color: Color(colors[0]).isDark() ? 'white' : '#111827' }}
            >
              Choose from a variety of color modes and pick your primary color.
              Then, you can copy the color palette to your clipboard and use it
              in your projects. Down below, you can see some components that use
              the color palette!
            </p>
          </div>
          <div className="mx-auto mt-16 max-w-lg rounded-lg bg-white  p-8 shadow-2xl sm:mt-24 lg:mt-0 lg:flex-shrink-0 lg:flex-grow">
            <div className="mt-10 flex items-center justify-center ">
              <ColorWheel
                color={inputColor}
                setColor={setInputColor}
                setColors={setColors}
                mode={mode}
              />
            </div>

            <div className="mx-5 mt-5 max-w-md sm:mx-auto">
              <PickPrimaryColor color={inputColor} setColor={setInputColor} />

              <SelectMode mode={mode} setMode={setMode} modes={modes} />

              <ColorPaletteGroup
                {...{
                  colors,
                  copied,
                  copyIndex,
                  copyToClipboard,
                }}
              />
            </div>
          </div>
        </div>

        <Components colors={colors} />
      </main>
    </>
  );
}
